### ISSUE TITLE
miscategorized version 102 release notes at https://www.thunderbird.net/en-US/thunderbird/releases/

### ISSUE THREAD

**Issue by wsmwk** [thundernest/thunderbird-notes#19]
https://www.thunderbird.net/en-US/thunderbird/releases/  
* has several version 102 release notes links listed under version 10.
* and 102.1.0, 102.1.1, 102.1.2 are not listed under 102.0

**Comment by Sancus** [comment]
https://github.com/thundernest/thunderbird-website/issues/325
