### ISSUE TITLE
Add subsections/grouping to release notes

### ISSUE THREAD

**Issue by Sancus** [thundernest/thunderbird-notes#3]
OK, so we need some way to group release notes into subsections for the different beta releases. Sticking in fake tags isn't good, because the notes are supposed to be a list of independent items, the front end display can be changed to anything, for example [Mozilla does each tag in its own section](https://www.mozilla.org/en-US/firefox/64.0/releasenotes/). If we start putting structure and style into the note data, we lose the ability to change the front-end without making a huge mess of all historical notes.

So I see two options:

1) Keep the notes list flat, and add a 'group' property to each note. The name of each group is in a list in a 'groups' list under the 'release' dictionary, and then you just add a group number property to each note. This keeps the 'notes' structure flat and relatively simple, and maybe more readable? But you have to enter the group number for each item.
```
release:
  release_date: 2018-12-30
  import_system_requirements: '60.0beta'
  groups:
  -
  - 'New and Fixed in Thunderbird 65 beta 2'

notes:
- note: 'Thunderbird now allows the addition of OpenSearch search engines from a local XML file
    using a minimal user inferface: [+] button to select a file an add, [-] to remove.
    Note: The set of search engines will be improved the next version, Google and DuckDuckGo will
    be available by default.'
  tag: new
  bug: 1427317
  group: 2
- note: 'During account creation, Thunderbird will now detect servers using the Microsoft Exchange protocol.
    It will offer the installation of a 3rd party add-on (Owl) which supports that protocol.'
  tag: new
  bug: 1500105
  group: 2
```
2) Add 'group' dictionaries into the list of notes. This avoids an additional property by adding structure, but it might be less readable due to the amount of nested data structures:
```
notes:
- note: 'FileLink for WeTransfer'
  tag: new
  bug: 1504508
- note: 'WebExtensions FileLink API to facilitate FileLink add-ons.
    WeTransfer is already included and Dropbox is available as [add-on](https://addons.thunderbird.net/en-US/thunderbird/addon/cloudfile-provider-for-dropbox/).'
  tag: new
  bug: 1511950
- group: 'New and Fixed in Thunderbird 65 beta 2'
  notes:
    - note: 'When multiple language packs are installed, the UI language can now be selected in the   Advanced Options.
      Preference
      intl.multilingual.enabled needs to be set (and possily also extensions.langpacks.signatures.required
      needs to be set to false)'
      tag: new
      bug: 1509977
    - note: 'Spellcheck marks disappeared erroneously for words with an apostrophe (working in Thunderbird ESR)'
      tag: unresolved
      bug: 1418629
```
Tell me which you like better, or if you have some other structure you would prefer.

**Comment by Sancus** [comment]
cc @darktrojan @jorgk3

**Comment by jorgk3** [comment]
I prefer option one as long as the group property isn't mandatory.

**Comment by Sancus** [comment]
This was implemented as option 1, the README is updated and the new template is live: https://www.thunderbird.net/en-US/thunderbird/66.0beta/releasenotes/
